
[general]

	[general.blocks]

		[general.blocks.pedestal]
			accept_any_item = true
			spawn_particles = true

	[general.relics]

		[general.relics.general]
			leveling_bar_style = "||||||||||||||||||||||||||||||"
			leveling_bar_color_neutral = "#808080"
			leveling_bar_color_low = "#FF5555"
			leveling_bar_color_medium = "#FFFF55"
			leveling_bar_color_high = "#55FF55"

		[general.relics.compatibility]
			warn_about_old_forge = true

